### ISSUE TITLE
TS45: Incorrect Chain Template format

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#107]
**Describe the bug**
1. First stop is not supplier
2. System requires at least 3 stops in a chain template.
3. System requires alternate warehouse and forwarder for the stops.

**To Reproduce**
1. Go to 'Logistics' then 'Chain Template'
2. Click on 'New Chain Template'
3. Enter details

**Expected behavior**
1. There should be no format/rule for the stops in the chain template. Supplier is usually the 1st stop. Then, there can be multiple successive forwarders as well. There should be no restriction.
2. There should be no minimum number of stops per chain template. A shipment can be directly delivered to site (supplier to site) so it can be less than 2 stops.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/65406673-d7a1e600-de12-11e9-8611-08d3788f091c.png)
![image](https://user-images.githubusercontent.com/51902789/65406470-43d01a00-de12-11e9-951d-415d34dff375.png)

**Additional Context:**
As discussed last time, if it is not possible to have the Supplier as the 1st stop, then we can do the 1st stop's first action as "Receive" so that they can indicate when they received the shipment from the supplier and then "Release". Currently, 1st stop only has "Release".

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by HannahCastro** [comment]
To add, since we cannot determine the time in the chain template for the time being, please hide the times fields.
![image](https://user-images.githubusercontent.com/51902789/65485262-fae09a00-ded3-11e9-8095-e8bee01643b2.png)
![image](https://user-images.githubusercontent.com/51902789/65485292-12b81e00-ded4-11e9-8d82-4d6cf6ea7293.png)

**Comment by HannahCastro** [comment]
Time fields have been hidden and fields/button have been renamed. There is also no restriction that storage location should be the first stop. However, system still required at least 2 stops.
![image](https://user-images.githubusercontent.com/51902789/67944383-527ecd80-fc17-11e9-80ba-8acd61c0f089.png)
Also, first stop receiver doesn't have the release button. Instead, system automatically indicated that shipment was received by the logistics coordinator.
![image](https://user-images.githubusercontent.com/51902789/67945203-514ea000-fc19-11e9-9865-3b0b3e05ae15.png)
![image](https://user-images.githubusercontent.com/51902789/67945260-72af8c00-fc19-11e9-96d6-8596cc586c3f.png)

**Comment by zetaleona** [comment]
Hi!

The "Release" button is under JO module which would be addressed on the next batches.

**Comment by HannahCastro** [comment]
> Hi!
> 
> The "Release" button is under JO module which would be addressed on the next batches.

Noted. Please note that since we are not able to make the supplier as the 1st stop, the actual 1st stop's action should be "Receive" first, then release.

As of November 5, you can now create chain templates with no restriction on the order and number of stops.
![image](https://user-images.githubusercontent.com/51902789/68171966-ce2ea080-ffb0-11e9-832b-994708ebff56.png)
![image](https://user-images.githubusercontent.com/51902789/68171970-d090fa80-ffb0-11e9-8f22-dbbbe3565c38.png)
![image](https://user-images.githubusercontent.com/51902789/68171973-d2f35480-ffb0-11e9-9116-025be17028d3.png)
This ticket is now resolved.
