### ISSUE TITLE
TS73: Fields for LC application appeared after submission of JO for approval. Also, fields can be seen by the Logistics Head and Canvasser.

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#109]
**Describe the bug**
Fields for LC application appeared after submission of JO for approval. Also, fields can be seen by the Logistics Head and Canvasser. 

**To Reproduce**
Canvasser, JO creation submission

**Expected behavior**
Fields highlighted in the image below should not be included/seen in the JO creation. These fields are under LC application and for Logistics Coordinator.

**Screenshots**
![image](https://user-images.githubusercontent.com/54825571/65411475-9532d600-de1f-11e9-9ad6-3327ee7bee7c.png)

**Comment by zetaleona** [comment]
Hi!

Just to clarify, LC Application will only be available for the Logistics Coordinator view or once the Logistics Coordinator Filled-up the LC Application, would it be available to other users?

**Comment by agiebanez** [comment]
> Hi!
> 
> Just to clarify, LC Application will only be available for the Logistics Coordinator view or once the Logistics Coordinator Filled-up the LC Application, would it be available to other users?

Hi! Once LC application has been filled-up. Following users should be able to view the details.
- Logistics Head
- Canvasser
- Logistics coordinator

LC application can only be edited by the Logistics coordinator. 
As per checking, this ticket is okay.

![JO LC](https://user-images.githubusercontent.com/54825571/70119943-64381280-16a6-11ea-9b6f-0444adf67be5.png)
![JO approval](https://user-images.githubusercontent.com/54825571/70119944-64381280-16a6-11ea-8407-14af32879d66.png)
![JO LH](https://user-images.githubusercontent.com/54825571/70120077-a5c8bd80-16a6-11ea-8a79-bfac032598b1.png)
