### ISSUE TITLE
TS78: Request for JO cancellation button is only available when JO is newly created

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#111]
**Describe the bug**
JO cancellation button is only available when JO is newly created.

**To Reproduce**
1. Go to 'PO Management' then 'View' for the PO to process
2. Scroll down to 'List of JO'
3. Click on 'View' for the JO to cancel

**Expected behavior**
Request for JO cancellation button should be available when JO is both pending approval, rejected, and approved (but with no transaction yet). Logistics Head will have to approve JO cancellation.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/65414495-708e2c80-de26-11e9-878e-176f8fe356aa.png)
![image](https://user-images.githubusercontent.com/51902789/65414525-813ea280-de26-11e9-9dd6-bf9e4a2dac76.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by zetaleona** [comment]
Hi! 

May we know when the transaction will be started? Is it when the logistics head assigns the JO to Logistics Coordinator or is it when the receiving and releasing of JO has been started.

**Comment by HannahCastro** [comment]
Requesting for cancellation of a JO can be done anytime. JO can either be new, unapproved, rejected, or approved, as long as there is no receiving done yet.

**Comment by zetaleona** [comment]
> Requesting for cancellation of a JO can be done anytime. JO can either be new, unapproved, rejected, or approved, as long as there is no receiving done yet.

This is noted. Thank you

**Comment by HannahCastro** [comment]
Canvasser can request to cancel JO even if JO is not newly created.
![image](https://user-images.githubusercontent.com/51902789/69316383-ad826e00-0c73-11ea-86ac-249e217e1b41.png)

This issue is now resolved.
