### ISSUE TITLE
TS135: QR code for MRM did not work for iOS/iPhone 6s.

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#133]
**Describe the bug**
I downloaded an app called QR reader. QR code for MRM did not work for iOS/iPhone 6s.
I used the QR reader app and successfully read the code. System automatically redirected to the url, however, it did not show the MRM or link

**To Reproduce**
Login egrn account on mobile, use QR reader app and scan the code.

**Expected behavior**
System should automatically redirect to the url / server once the code is scanned.

**Smartphone (please complete the following information):**
 - Device:  iPhone6s
 - OS: iOS
 - Browser :Safari 
 - Version: 12.4.1

![viber_image_2019-09-25_14-50-16](https://user-images.githubusercontent.com/54825571/65576978-87a75880-dfa5-11e9-9573-0dfaf86de5e6.jpg)

**Comment by HannahCastro** [comment]
@matthewroman for your assistance in closing this ticket.

**Comment by VCI-Jojo** [comment]
@HannahCastro Closing ticket as per previous comment.
