### ISSUE TITLE
TS140.1: Chain template set by the Logistics Head and the tracking is not aligned

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#138]
**Describe the bug**
Chain template set by the Logistics Head and the tracking is not aligned

**Expected behavior**
Chain template must always be aligned.

**Screenshots**
![chain 1](https://user-images.githubusercontent.com/54825571/65583018-0bb30d80-dfb1-11e9-87a9-287621c25f02.png)

**Comment by HannahCastro** [comment]
This is similar to tickets #72 and #184. The Chain Template indicated by the Logistics Coordinator doesn't match the chain template indicated in the Order Tracking.
