### ISSUE TITLE
TS147: System didn't allow Site Receiver to proceed with JO with "Partial Delivery" exception

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#139]
**Describe the bug**
System didn't allow completing JO if a line item has an exception tagged as "Partial Delivery". There was no prompt or error message. "Complete JO" button didn't work so system didn't proceed to MRM preparation. When you click on the exception again, the exception indicated wasn't saved.

**To Reproduce**
1. Go to notifications
2. Click on 'Released Shipping'
3. Enter quantity received (ex. 5)
4. Click on the exceptions button and indicate exception as "Partial Delivery"
5. Click on 'Save'
6. Click on 'Complete JO'
7. See error

**Expected behavior**
System should allow receiver to proceed to MRM preparation for partial deliveries. System will tag the JO as Partially Delivered/Partially Delivered with Exceptions (depending on whether or not there are other exceptions indicated such as damage, missing). System should still allow user to receive the remaining quantity at a future time/date. Different MRM will be created.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/65584262-31d9ad00-dfb3-11e9-92db-b92632687929.png)
![image](https://user-images.githubusercontent.com/51902789/65584294-3dc56f00-dfb3-11e9-8a9b-dd3234f4e313.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by LAValera** [comment]
This   issue has been addressed but some related issues persist (MRM creation for excess quantities in delivery under 1 PO but multiple JOs)

**Comment by zetaleona** [comment]
> This issue has been addressed but some related issues persist (MRM creation for excess quantities in delivery under 1 PO but multiple JOs)

Hi! Please create separate tickets for any related issues, so we can address each one. Thank you.

**Comment by HannahCastro** [comment]
Receiving of "Partial Delivery" is now working. JO status is tagged as Delivered. Remaining Quantity can be received at another time. Once full quantity has been received, JO status will be "Fully Delivered".

Ticket for error regarding receiving of excess items have been created (#186).
