### ISSUE TITLE
TS155: Supplier name and project name were not integrated in the MRM and has to be typed manually. Should be integrated.

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#141]
**Describe the bug**
Supplier name and Project name were not integrated in the MRM and has to be typed manually. 

**Expected behavior**
Supplier name and Project name must be integrated in the MRM preparation. 
Please also change "Received from" to "Supplier name"

**Screenshots**
![mrm prep](https://user-images.githubusercontent.com/54825571/65586500-d90c1380-dfb6-11e9-808a-0787241ff74d.png)

**Comment by zetaleona** [comment]
Hi!

Where do we get the"Project Name" for MRM Preparation?
Currently, we don't have a field provided for the  Project Name in the system.

**Comment by agiebanez** [comment]
Supplier name and project name are now integrated.

![mrm rec com](https://user-images.githubusercontent.com/54825571/70120822-5e433100-16a8-11ea-8a2f-b66460689dc6.png)
