### ISSUE TITLE
Additional field for remarks/comments and photo attachments in the "receiving" and "releasing"stage for each stop in the chain template. 

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#146]
**Is your feature request related to a problem? Please describe.**
During the receiving and releasing stage in the chain template, if the receiver have concerns on the delivery (example, damage/missing, etc), there's no option/field for the receiver to comment or put remarks as well as photo attachments for the items received. 

This feature is needed to immediately address the concerns and resolve the issues of the parties involved. 

**Describe the solution you'd like**
All stops in the chain template during receiving and releasing stage should have a field for the user to comment or put remarks on the delivery as well as photo attachments of the items received. These fields are required. Users to be notified are the Canvasser, Logistics Coordinator, Logistics Head, and next receiver. 

![RECEIVER COMMENTS](https://user-images.githubusercontent.com/54825571/65652287-d0155380-e043-11e9-9db2-26e8721cccd5.png)

**Comment by HannahCastro** [comment]
Each stop in the chain template now has the option to include remarks and photo during receiving/releasing stage. This issue is now resolved.
