### ISSUE TITLE
TS147: Status in final receiving is only "Delivered"

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#149]
**Describe the bug**
The JO status in final receiving is only "Delivered". We cannot determine if this is partially delivered or fully delivered.

**Expected behavior**
Status for the JO should be differentiated so that it will be easier to determine at first glance.
1. Fully Delivered - (a) when the received quantity is equal to the expected quantity (b) when exception tagged is "Excess"
2. Partially Delivered - when exception tagged is "Partial Delivery"
3. Partially Delivered with Exceptions - when there is an exception tagged that is not "Partial Delivery" (ex. Damaged, Missing)

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/65670236-89415100-e077-11e9-9193-649fb0075221.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by LAValera** [comment]
JO   status reflects "Partially Delivered" when exception tagged is "Excess". Expected behavior is for JO status to reflect "Fully   Delivered" when exception tagged is "Excess"

**Comment by HannahCastro** [comment]
Fully Delivered status is now available. This status will appear when Expected Quantity was received.
![image](https://user-images.githubusercontent.com/51902789/80700251-f1757b00-8b0f-11ea-8829-fa6fd122296f.png)
