### ISSUE TITLE
TS184: No collated result for the evaluation/QA/QC

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#159]
**Describe the bug**
There is no function to view collated result for the evaluation/QA/QC.

**To Reproduce**
1. Go to 'Pending Review'
2. Filter results
3. See error

**Expected behavior**
System should average the results based on the number of evaluations provided.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/65737233-7169db80-e110-11e9-9b5b-48bf88047b70.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by LAValera** [comment]
Issues unresolved

**Comment by HannahCastro** [comment]
> Issues unresolved

There is still no average results for a certain forwarder, etc.

**Comment by HannahCastro** [comment]
Average Results is now available in Pending Review.
![image](https://user-images.githubusercontent.com/51902789/80796341-842a1e80-8bd1-11ea-8209-9f3585a91cec.png)
![image](https://user-images.githubusercontent.com/51902789/80796394-a2901a00-8bd1-11ea-8bd5-93d151f615d3.png)
![image](https://user-images.githubusercontent.com/51902789/80796488-dcf9b700-8bd1-11ea-90f1-9a0cf46305d8.png)
