### ISSUE TITLE
TS62: No pop-up message to confirm completion of PO

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#164]
**Describe the bug**
System didn't show pop-up message to confirm completion of PO.

**To Reproduce**
1. Go to 'PO Management'
2. Create PO
3. Click on 'Submit PO'
4. Click on 'Complete PO'
5. See error

**Expected behavior**
Same as the pop-up message when canvasser submits PO, there should also be a pop-up message when completing the PO.
Please note that all transactions should have a pop-up message so that users know if the action done has been accepted by the system. This happened to assigning to Logistics Coordinator, as well.

**Screenshots**
Pop-up message shown when 'Submit PO' is clicked. No such message is show when 'Complete PO' is clicked.
![image](https://user-images.githubusercontent.com/51902789/65744907-85bbd180-e12c-11e9-9b04-51a0a0aae008.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by HannahCastro** [comment]
As of November 14, a pop-up message has been added to signify that PO was completed and saved.
![image](https://user-images.githubusercontent.com/51902789/68818400-cf9e4e00-06bf-11ea-8a7e-4cefaa91ac3a.png)
![image](https://user-images.githubusercontent.com/51902789/68818402-d0cf7b00-06bf-11ea-9685-a425a8d5fa87.png)

**Comment by HannahCastro** [comment]
Upon checking, there is still no pop-up message when Logistics Head assigned JO to Logistics Coordinator.
![image](https://user-images.githubusercontent.com/51902789/68833681-08a1e700-06ef-11ea-9fcf-e876096ff317.png)
![image](https://user-images.githubusercontent.com/51902789/68833791-4ef74600-06ef-11ea-88d0-569e432735dd.png)

**Comment by zetaleona** [comment]
Hi!

kindly create a new chain template and use it instead, because the old chain templates have bugs.
We still need to clean some dummy data.
Thank you.

**Comment by zetaleona** [comment]
> Upon checking, there is still no pop-up message when Logistics Head assigned JO to Logistics Coordinator.
> ![image](https://user-images.githubusercontent.com/51902789/68833681-08a1e700-06ef-11ea-9fcf-e876096ff317.png)
> ![image](https://user-images.githubusercontent.com/51902789/68833791-4ef74600-06ef-11ea-88d0-569e432735dd.png)

Hi!

kindly create a new chain template and use it instead, because the old chain templates have bugs.
We still need to clean some dummy data.
Thank you.

**Comment by HannahCastro** [comment]
> > Upon checking, there is still no pop-up message when Logistics Head assigned JO to Logistics Coordinator.
> > ![image](https://user-images.githubusercontent.com/51902789/68833681-08a1e700-06ef-11ea-9fcf-e876096ff317.png)
> > ![image](https://user-images.githubusercontent.com/51902789/68833791-4ef74600-06ef-11ea-88d0-569e432735dd.png)
> 
> Hi!
> 
> kindly create a new chain template and use it instead, because the old chain templates have bugs.
> We still need to clean some dummy data.
> Thank you.

Hello, we tried this for JOs without the chain templates (to be encoded by assigned Logistics Coordinator). When Logistics Head assigns JO to Logistics Coordinator, page just refreshes in order for the "Approve" button to not be grayed out. Value in the dropdown list appears as just "Select Logistics Coordinator" even if it was assigned successfully.
![image](https://user-images.githubusercontent.com/51902789/69107968-2b951800-0aae-11ea-989e-fe42eee00b2e.png)

**Comment by HannahCastro** [comment]
PO has notification for completion of PO.
![image](https://user-images.githubusercontent.com/51902789/74617251-2c018580-5167-11ea-94c7-a83c0df4b4a7.png)
![image](https://user-images.githubusercontent.com/51902789/74617257-37ed4780-5167-11ea-9ffb-17917ed2e95c.png)
System asked if JO will be assigned to the Logistics Coordinator. System reflected the name of the processor once Logistics Head clicks "Yes".
![image](https://user-images.githubusercontent.com/51902789/74617467-1a6cad80-5168-11ea-94ce-34738d9e9e57.png)
![image](https://user-images.githubusercontent.com/51902789/74617488-3708e580-5168-11ea-903f-fcd0ec31fbdb.png)
