### ISSUE TITLE
TS95: System didn't notify canvasser for approved JO

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#166]
**Describe the bug**
System didn't notify canvasser of the approved JO.

**To Reproduce**
1. Go to notifications
2. See error

**Expected behavior**
System should be notified of the status of their approved JO.

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by zetaleona** [comment]
Hi!

This is a duplicate request. 
Ticket #67-TS87 and Ticket #131-TS160

**Comment by HannahCastro** [comment]
> Hi!
> 
> This is a duplicate request.
> Ticket #67-TS87 and Ticket #131-TS160

Will edit this request to just notification for approved JOs.
Ticket #67 is for rejected JOs.
Ticket #131 is for approved MRMs.

**Comment by HannahCastro** [comment]
Canvasser is now notified when the JO they created has been approved.
![image](https://user-images.githubusercontent.com/51902789/76043559-de707f80-5f92-11ea-861e-11f969efa60a.png)

This issue is now resolved.
