### ISSUE TITLE
Uploading PO and line item data as basis for PO and Product Type List

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#179]
**Is your feature request related to a problem? Please describe.**
In relation to ticket #s 8, 174, and 56, it will be hard if we maintain an item database in eGRN that is why we suggested removing Product Type List and manually encoding items in the PO. We have assumed that when integration is up, data will just be transferred.

**Describe the solution you'd like**
If integration is not yet ready, we are suggesting that we upload excel files of the PO. The system will be saving the PO and line item data based on the PO data uploaded. The line item data will then populate the Product Type List. The following fields for the line items/BOQ are as follows:
-Item/Part #
-Commodity
-Product Name
-Quantity
-UOM

**Additional context**
Please see example of PO data from our current e-Procurement system.
![image](https://user-images.githubusercontent.com/51902789/66188514-fda07380-e6b9-11e9-9544-f67d57b9ec84.png)

**Comment by zetaleona** [comment]
Hi!

May we request for a sample e-Procurement output file so we can test the upload functionality. Thank you.

**Comment by HannahCastro** [comment]
> Hi!
> 
> May we request for a sample e-Procurement output file so we can test the upload functionality. Thank you.

Please see attached files.
[01PO_ITM20190614.xlsx](https://github.com/vasavah/vsv-fli-grn/files/3777608/01PO_ITM20190614.xlsx)
[01PO_DTL20190614.xlsx](https://github.com/vasavah/vsv-fli-grn/files/3777609/01PO_DTL20190614.xlsx)
[01PO_HDR20190614.xlsx](https://github.com/vasavah/vsv-fli-grn/files/3777611/01PO_HDR20190614.xlsx)
[01PO_ITM20190318.xlsx](https://github.com/vasavah/vsv-fli-grn/files/3777819/01PO_ITM20190318.xlsx)
[01PO_DTL20190318.xlsx](https://github.com/vasavah/vsv-fli-grn/files/3777820/01PO_DTL20190318.xlsx)
[01PO_HDR20190318.xlsx](https://github.com/vasavah/vsv-fli-grn/files/3777821/01PO_HDR20190318.xlsx)

**Comment by zetaleona** [comment]
Hi!

What specific fields do you need to be reflected in the product type?

**Comment by HannahCastro** [comment]
> Hi!
> 
> What specific fields do you need to be reflected in the product type?

These are the most important fields needed in the product type listing
1. Item Code, if available
2. UOM
3. Item Description (i.e. the name of the item)
Other fields such as the photo, item category, supplier, and packing type are not required.

**Comment by zetaleona** [comment]
> > Hi!
> > What specific fields do you need to be reflected in the product type?
> 
> These are the most important fields needed in the product type listing
> 
> 1. Item Code, if available
> 2. UOM
> 3. Item Description (i.e. the name of the item)
>    Other fields such as the photo, item category, supplier, and packing type are not required.

This is noted. Thank you.

**Comment by HannahCastro** [comment]
Upload of excel file is now available. System gets the data from the uploaded file and inputs it in the database.
Please note that there was a specific template that worked for this upload functionality. 
[01PO_ITM20190614.xlsx](https://github.com/vasavah/vsv-fli-grn/files/3872275/01PO_ITM20190614.xlsx)
![image](https://user-images.githubusercontent.com/51902789/69291500-6928ab00-0c3e-11ea-8446-8bb283777050.png)
![image](https://user-images.githubusercontent.com/51902789/69291523-7a71b780-0c3e-11ea-97ee-54ebc55d5054.png)
![image](https://user-images.githubusercontent.com/51902789/69291497-65952400-0c3e-11ea-8dc5-87099aa4af7a.png)
![image](https://user-images.githubusercontent.com/51902789/69291509-6cbc3200-0c3e-11ea-8dad-57faeabb4a96.png)
![image](https://user-images.githubusercontent.com/51902789/69291510-6fb72280-0c3e-11ea-8b15-634274fcab35.png)
![image](https://user-images.githubusercontent.com/51902789/69291513-72197c80-0c3e-11ea-932d-19ebdf5166df.png)
![image](https://user-images.githubusercontent.com/51902789/69291519-747bd680-0c3e-11ea-96b0-9589ab1f7bf3.png)


This issue is now resolved.
