### ISSUE TITLE
There is an approval workflow for POs

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#183]
**Describe the bug**
To address ticket #37, as discussed, only approved POs should be in eGRN. There should be no approval workflow for POs. 

**To Reproduce**
1. Go to 'PO Management'
2. Click on 'Create New PO'
3. Enter PO details, submit PO, then complete PO

**Expected behavior**
For integrated POs, only approved ("Awarded") POs should be relayed to the system. If there is no integration, approved POs will be manually transferred to eGRN. "Complete PO" serves as the "awarding" or "approving" and should only be done by the canvasser-in-charge.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/68661574-239d1b80-0576-11ea-90bb-82f1225f6517.png)
![image](https://user-images.githubusercontent.com/51902789/68661581-26980c00-0576-11ea-8cbf-fd50a4d700c1.png)
![image](https://user-images.githubusercontent.com/51902789/68661586-27c93900-0576-11ea-9e8d-f8189f098c5e.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Additional context**
The main concern being raised in ticket #37 is the access issues, that a user not assigned/related to the PO can see and use the PO already.

**Comment by zetaleona** [comment]
Hi!

May we know which specific user or users can view the awarded POs?

**Comment by HannahCastro** [comment]
> Hi!
> 
> May we know which specific user or users can view the awarded POs?

Only assigned users should be able to view the documents. Admin and Logistics Head should be able to see all.

So for a certain PO, if integrated, the canvasser-in-charge should be able to view the PO (ex. PO1234567890 was created by user A. Only user A (and admin) should be able to see this. In turn, if a PO is manually encoded, the canvasser who encoded it should only be able to view the PO. This is the case for the other documents as well (JO, MRM, NCR, MRS, MIS). It should only be seen by the respective user (whether logistics coordinator, forwarder, PTH/PIC, site engineer, etc.).

Example: User A created PO. Only user A will be able to view the PO in order to create the JO. Once JO is forwarded for approval, JO will be seen by canvasser-in-charge, logistics head, and admin. Then, logistics coordinator will only be able to see JO if it was assigned to them. PTH/PIC assigned will only be able to see specific JO that was forwarded to them for Date Needed at Site confirmation. Respective forwarders and site engineers will only be able to see the JOs assigned to them for approval. Assigned PTH/PIC will only be able to see the respective MRMs for approval.

**Comment by HannahCastro** [comment]
Approval workflow for POs has been removed.
![image](https://user-images.githubusercontent.com/51902789/74726801-0c5b8180-527b-11ea-9782-40af22423126.png)
![image](https://user-images.githubusercontent.com/51902789/74726805-0e254500-527b-11ea-8a8d-948966844fd7.png)
![image](https://user-images.githubusercontent.com/51902789/74726818-154c5300-527b-11ea-984e-87c614f4b781.png)
![image](https://user-images.githubusercontent.com/51902789/74726829-18474380-527b-11ea-8096-248550f0a0d5.png)
![image](https://user-images.githubusercontent.com/51902789/74726852-2301d880-527b-11ea-9a2b-d5da0a899ec9.png)

This issue has been resolved.
