### ISSUE TITLE
4-17-20 Wrong "remaining quantity" in JO

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#185]
**Describe the bug**
The JO has an error in the total quantity of created JOs

**To Reproduce**
Create a PO then create a JO with partial quantity (e.g. 4000 out of 10000) then create another JO and see error

**Expected behavior**
The sum of the total quantity should match the quantity in the JOs created.

**Screenshots**
![image](https://user-images.githubusercontent.com/54824392/79552512-b3b73200-80cd-11ea-97c4-3215659d8e67.png)
![image](https://user-images.githubusercontent.com/54824392/79552544-c0d42100-80cd-11ea-91f3-5560df98b9c1.png)
![image](https://user-images.githubusercontent.com/54824392/79552987-65eef980-80ce-11ea-89f6-02301fb97f74.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-Bit (10.0, Build 18362)
 - Browser: Chrome
 - Version: 80.0.3987.163 (Official Build) (64-bit)

**Comment by VCI-Jojo** [comment]
@HannahCastro Kindly validate on your end so we can close this ticket. Thank you.

**Comment by HannahCastro** [comment]
@VCI-Jojo Except for the attachment, I made a PO similar to the one in this ticket. JO was created.
![image](https://user-images.githubusercontent.com/51902789/82526832-872c8500-9b67-11ea-8ad3-0f433a957799.png)
![image](https://user-images.githubusercontent.com/51902789/82526878-aa573480-9b67-11ea-8be8-f2ccdc0a3193.png)
![image](https://user-images.githubusercontent.com/51902789/82526909-bba04100-9b67-11ea-96d6-3cadbf379ee6.png)

@LAValera Kindly validate as well using same details as the one you used.

**Comment by LAValera** [comment]
@HannahCastro I tested this scenario again. System prompts user already if JOs created exceed the PO quantity.
