### ISSUE TITLE
QR code to be emailed to supplier and logistics

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#199]
**Is your feature request related to a problem? Please describe.**
As the purpose of the system is to make receiving easier, QR code should be in the shipment.

**Describe the solution you'd like**
QR code will be emailed to Supplier and Logistics. QR code will be printed and included in the shipment so that scanning of QR code will be easier.

**Comment by VCI-Jojo** [comment]
@HannahCastro As discussed during our meeting, this is pending SCM for the detailed the process on QR code sending. Thank you.

**Comment by HannahCastro** [comment]
@VCI-Jojo I'll get Logistics final direction on this.

**Comment by HannahCastro** [comment]
Closing ticket for now.
