### ISSUE TITLE
Checksum/Checkdigit for QR code authentication

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#201]
**Is your feature request related to a problem? Please describe.**
QR code authentication

**Describe the solution you'd like**
To include checksum/checkdigit for QR code authentication.

**Comment by HannahCastro** [comment]
@matthewroman if this has been validated, can we close the ticket?

**Comment by matthewroman** [comment]
Hi Hanna, yes this has been validated.  As mentioned, the security of the
QR code is actually validated server-side, which is more secure as
checksums can't be spoofed.

**Comment by HannahCastro** [comment]
@matthewroman if this is the case, can we close the ticket?

**Comment by matthewroman** [comment]
Yes maam

**Comment by HannahCastro** [comment]
Noted, we'll close the ticket.





Thank you and regards,


Hannah Castro

e-Procurement, Supply Chain Management

Filinvest Alabang Inc.

7th Flr. Vector One Bldg., Northgate Cyberzone,

Filinvest City, Alabang, Muntinlupa

Tel. No.: 846-0278 loc. 7053

________________________________
