### ISSUE TITLE
TS129: Fowarder Bidding - System were able to notify Canvasser but not the Logistics head. Should notify both.

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#21]
**Describe the bug**
Logistics coordinator has to input all the required fields for Forwarding Bidding. System were able to notify Canvasser about the changes but not the Logistics head. Should notify both.

**To Reproduce**
1. Go to 'PO Management'
2. Click on 'View'
3. Scroll down to 'Shipment details'

**Expected behavior**
Should notify both Logistics coordinator and Canvasser. Should not require the user to fill-up all the fields. But once details are encoded, details cannot be editable.

**Screenshots**
![FRWRDR BID](https://user-images.githubusercontent.com/54825571/64159315-9d28d700-ce6c-11e9-8aaf-c435d7e8c5ad.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by agiebanez** [comment]
"Add shipment details" button/option not available for Logistics coordinator.
Name of the assigned Logistics coordinator not showing.

![forwarder ship](https://user-images.githubusercontent.com/54825571/69131848-ded13180-0aed-11ea-9ab7-3f45674a6bcb.png)

**Comment by HannahCastro** [comment]
> "Add shipment details" button/option not available for Logistics coordinator.
> Name of the assigned Logistics coordinator not showing.
> 
> ![forwarder ship](https://user-images.githubusercontent.com/54825571/69131848-ded13180-0aed-11ea-9ab7-3f45674a6bcb.png)

For the name of the Logistics Coordinator, this is related to ticket #165.
