### ISSUE TITLE
TS143: Clicking Receive Goods will automatically proceed to encoding of Received Quantity

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#216]
**Describe the bug**
For the final receiver of a JO, when 'Receive Goods' is clicked, it will automatically proceed to the next step of encoding the Received Quantity.

**To Reproduce**
1. Go to JO to be received
2. Click on 'Receive Goods'
3. See error

**Expected behavior**
As QA/QC will be done, an extra step should be added so that user doesn't automatically go to encoding of received quantity. So when final receiver clicks on 'Receive Goods', system shouldn't automatically redirect to the next step. User will need to click on the button 'Finalize Receiving' to proceed to encoding of received quantity.

**Desktop (please complete the following information):**
-  OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by VCI-Jojo** [comment]
@HannahCastro What does the extra step entail? QA/QC is a different person than the Final Receiver that would note the good and tag the exceptions, wouldn't this be the Final Receiver also?

**Comment by HannahCastro** [comment]
@VCI-Jojo This is because counting of the received items (if all are in good condition or with exceptions) may occur at another day. This usually happens for bigger shipments and construction materials so they will receive it first then do the QA/QC. Quantities to be received will be determined after this.

**Comment by HannahCastro** [comment]
Closing this ticket for now.
