### ISSUE TITLE
TS75: When editing the rejected JO, system allows to change the item quantity and still proceed with JO creation even if the quantity exceeds the PO already.

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#24]
**Describe the bug**
When editing the rejected JO, system allows to change the item quantity and still proceed with JO creation even if the quantity exceeds the PO already.

**To Reproduce**
Go to Job Order, Click "View" on the rejected PO number and click on the "Edit Job Order". Scroll down on the Bill of Quantities. 

**Expected behavior**
User should be prompted and system should not allow user to go over to PO quantity based on the total JOs created already. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54824392/64223019-c9903200-cf04-11e9-914a-aab2ec973a50.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - Browser [Chrome]
 - Version [ 76.0.3809.132 (Official Build) (64-bit)]

**Comment by HannahCastro** [comment]
To add, when a rejected JO is edited, the system created a separate entry for that same JO Number (1 JO with Rejected status and 1 JO with New status).
![image](https://user-images.githubusercontent.com/51902789/64756220-b7e00780-d560-11e9-94cd-ecbe0001bb83.png)
Instead, the Rejected JO that was edited will still be retained. Once canvasser submits the JO, the status of the JO will be Pending Approval. We should be able to see in the audit trail that this JO was rejected for this certain reason and then resubmitted for approval.

**Comment by LAValera** [comment]
System prompts user if the JO quantity is more than the PO quantity or balance quantity. System also returns the quantity if a JO is rejected or cancelled.
