### ISSUE TITLE
TS130: System did not prompt the error and allowed Logistics Coordinator to proceed. Should not require the user to input all the fields and must still be able to proceed.  But once details are encoded, details cannot be editable.

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#26]
**Describe the bug**
System did not prompt the error. 
Should not require the user to fill-up all the fields. User must still be able to proceed.  But once details are encoded, details cannot be editable.

**To Reproduce**
1. Go to 'Job Order'
2. Click on 'View'
3. See error

**Expected behavior**
Should not require the user to fill-up all the fields. User must still be able to proceed.  But once details are encoded, details cannot be editable.

**Comment by zetaleona** [comment]
Hi!

Can we get the list of the required fields for the creation of JO?

Ex. 
1. Mode of shipment and point of destination are required
2. Date Needed at the site is not required

For Canvasser, Logistics Head, Logistics Coordinator, Supplier, Admin, PTH/PIC, etc., May we request the list of fields in the JO that specific user can view.

**Comment by agiebanez** [comment]
> Hi!
> 
> Can we get the list of the required fields for the creation of JO?
> 
> Ex.
> 
> 1. Mode of shipment and point of destination are required
> 2. Date Needed at the site is not required
> 
> For Canvasser, Logistics Head, Logistics Coordinator, Supplier, Admin, PTH/PIC, etc., May we request the list of fields in the JO that specific user can view.

**Comment by agiebanez** [comment]
Hi! You may refer to ticket #58 .

**Additional info**
Required :
- Delivery terms
- Mode of shipment 
- Chain template (Once JO is assigned to the Logistics Coordinator, he/she must be able to change / edit. )
