### ISSUE TITLE
TS81: JO Cancellation proceeds even without any explanation or reason

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#33]
**Describe the bug**
No function for putting remarks/reason for cancellation. You may request cancellation of JO even without any remarks or explanation.

**To Reproduce**
Go to PO Management and select View for PO of choice. Scroll down to List of JO and select View of JO of choice and see the error.

**Expected behavior**
Provide a field for remarks/explanation of canvasser for JO cancellation and prompt user if this is not filled up whenever they click on the request cancellation of JO button.

**Screenshots**
![image](https://user-images.githubusercontent.com/54824392/64229607-d456c100-cf1c-11e9-8701-a6f3cad8cce7.png)

**Desktop (please complete the following information):**
 - OS: [Windows 8.1]
 - Browser [Chrome]
 - Version [ 76.0.3809.132 (Official Build) (64-bit)]

**Comment by HannahCastro** [comment]
To add, JO cancellation should be also available even when (1) JO is not newly created but not yet approved and (2) JO has been approved.
