### ISSUE TITLE
Simultaneous Testing 1- Unapproved PO is posted to all user access and various users have same function as Canvasser

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#37]
**Describe the bug**
PO was not yet approved by canvasser but is already posted in Logistics Coordinator, Logistics Head, Forwarder, Supplier's user access. Supplier user access was able to do same function as canvasser. 

**To Reproduce**
Different users were done simultaneously and when canvasser created a new PO even without approval yet, different users were able to see the PO as posted and different users were able to do same functions as canvasser.
**Expected behavior**
New PO should be approved by Logistics Head first before the new PO will be posted as approved. A PO should be approved first before it can be seen as approved by various users.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HannahCastro** [comment]
Currently, the assigned canvasser, admin, and logistics head can see the created POs. Once approval workflow is removed, Logistics Head should only be able to see the POs when a corresponding JO has been forwarded to him/her for approval, not beforehand.

**Comment by HannahCastro** [comment]
Logistics Coordinator and Supplier can see POs that are not assigned to them. For the other accounts, this is not an issue anymore.
![image](https://user-images.githubusercontent.com/51902789/69390075-03edbc00-0d09-11ea-8302-4855382fc770.png)
![image](https://user-images.githubusercontent.com/51902789/69390304-c0e01880-0d09-11ea-8fa9-40e16f0eb5fe.png)
