### ISSUE TITLE
TS47: Edit button is missing in Chain Template module

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#46]
**Describe the bug**
Edit button in Chain Template module is missing.

**To Reproduce**
1. Go to 'Logistics' then 'Chain Template'
2. See error

**Expected behavior**
An Edit button should be available so that user can edit an existing Chain Template entry (if data is not applicable anymore).

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/64578294-8ecd4480-d3b1-11e9-8e41-3a107f136456.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by HannahCastro** [comment]
As of October 31, not all chain templates have the edit button.
![image](https://user-images.githubusercontent.com/51902789/67943863-fcf5f100-fc15-11e9-8e8c-6f8a7cd6884a.png)

**Comment by zetaleona** [comment]
Hi!

Once a chain template has been used on a JO, edit functionality is disabled so as to not affect the previously created JOs with the chain template.

**Comment by HannahCastro** [comment]
> Hi!
> 
> Once a chain template has been used on a JO, edit functionality is disabled so as to not affect the previously created JOs with the chain template.

We understand that a used chain template can't be edited as it will affect the JOs where it was used. However, if we are not able to edit a certain chain template, the data may not be factual anymore (i.e. cost and number of days). There are situations where a shipment will be stored in a certain stop (ex. a forwarder) for a certain number of days so it will incur additional cost. How can we include in the system, whether in the JO or the chain template itself, that there was additional cost and days incurred for the shipment?

**Comment by zetaleona** [comment]
Hi!

**Comment by zetaleona** [comment]
Hi!

We suggest that editing of the cost and number of days will be placed under the tracking of JO.

**Comment by HannahCastro** [comment]
> Hi!
> 
> We suggest that editing of the cost and number of days will be placed under the tracking of JO.

Noted. If this is the case, we will close this ticket now as editing function is working. 
We just want to make sure that editing of these 2 is allowed and won't affect existing transactions. New ticket (#182) was created for this suggestion.
