### ISSUE TITLE
Audit trail for user management is missing

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#5]
**Describe the bug**
Audit trail for user management and all related functions is missing in the account. Audit trail listing is currently under 'Activity' in 'Reports'.

**To Reproduce**
_For admin users:_
1. Go to 'Users Management'
2. Click on 'Click to View' for specific account to view
3. See error
_For non-admin users:_
1. Go to 'My Profile'
2. See error

**Expected behavior**
1. 'Activity' under 'Reports' should be removed.
2. Audit trail for accounts should be in the account of the admin and the user involved and should be available for the users. Date, time and specific activity should be noted.
3. Admin should be able to view all listings in the audit trail (even those activities done by non-admin users) while non-admin users will only be able to view limited data in their audit trail. Please see below for matrix on audit trail listing:
![image](https://user-images.githubusercontent.com/51902789/64088995-8ef88f00-cd76-11e9-9153-0da09f4e969a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/64092197-4648d200-cd86-11e9-93dc-a8770bf3101c.png)
![image](https://user-images.githubusercontent.com/51902789/64088039-23acbe00-cd72-11e9-95a3-027c08d263f3.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Additional context**
_Audit trail found in PASS for reference_
![image](https://user-images.githubusercontent.com/51902789/64089062-dc74fc00-cd76-11e9-8e8d-0266807368ca.png)

**Comment by LAValera** [comment]
Audit trail on Administrator account under User Management only logs admin activities and does not log activities related to PO and JO management

**Comment by HannahCastro** [comment]
Closing this ticket. Audit trail for transactions has been reported in another ticket.
