### ISSUE TITLE
TS74: Notification of rejected JOs is absent in canvasser view

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#51]
**Describe the bug**
Created JO was rejected by PTH but there was no notification of rejection seen in the canvasser's user access.
**To Reproduce**
1. Create a JO
2. PTH will reject the JO
3. Go to notifications and check if there are any updates
4. Go to JO list and see rejected status

**Expected behavior**
Canvasser should be notified of the rejection. It should appear in the notifications not just in the JO list.

**Screenshots**
![image](https://user-images.githubusercontent.com/54824392/64684208-45671d00-d4b7-11e9-9b3e-e9e35a783c64.png)
![image](https://user-images.githubusercontent.com/54824392/64684253-5879ed00-d4b7-11e9-9139-96f22d1d4636.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Chrome]
 - Version [Version 76.0.3809.132 (Official Build) (64-bit)]

**Comment by zetaleona** [comment]
Hi, 

May we know who's the one will reject JO? is it Logistics Head or PTH/PIC?
Thank you.

**Comment by agiebanez** [comment]
Logistics Head will approve or reject the JO. PTH/PIC will confirm or change the date needed on site found in the JO.

**Comment by LAValera** [comment]
Canvasser is notified of rejection.
