### ISSUE TITLE
TS142: Forwarder was notified about the pending goods for receiving as well as the next receiver. But not the Logistics coordinator and Canvasser

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#64]
**Describe the bug**
Logistics Coordinator and Canvasser was not notified about the updates.

**Expected behavior**
Forwarder was notified about the pending goods for receiving as well as the next receiver. 

But Logistics Coordinator and Canvasser and must also be notified about the updates.

**Screenshots**
![image](https://user-images.githubusercontent.com/54825571/64776460-d529cb80-d58a-11e9-9d51-7056eb946818.png)

**Comment by HannahCastro** [comment]
We saw that notification for Logistics Coordinator and Canvasser are inconsistent. They are not always notified.
![image](https://user-images.githubusercontent.com/51902789/65577192-ee2c7680-dfa5-11e9-9f96-bc79c7466135.png)
