### ISSUE TITLE
TS144: Once received, system automatically redirects to MRM creation. But when you click other module, you cannot go back to create the MRM and no option for MRM creation.

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#65]
**Describe the bug**
Once received, system automatically redirects to MRM creation. But when Once received, system automatically redirects to MRM creation. But when you click other module, you cannot go back to create the MRM and no option for MRM creation.

**Expected behavior**
Once received, system should redirect to MRM creation but in case user mistakenly clicked other module, user must still be able to go back on the previous module.

**Screenshots**
![image](https://user-images.githubusercontent.com/54825571/64777326-81b87d00-d58c-11e9-8095-6426c750a6ad.png)

**Comment by agiebanez** [comment]
Still no option for the user to go back on the previous module. 
Submission of MRM not working. 

Project name should be system generated.

![mrm receiving](https://user-images.githubusercontent.com/54825571/69041451-7cfbc380-0a2a-11ea-97da-c48a7fa3491a.png)
![mrm receiving 1](https://user-images.githubusercontent.com/54825571/69041445-7c632d00-0a2a-11ea-9869-b6bf2e682f92.png)
![mrm receiving 2](https://user-images.githubusercontent.com/54825571/69041447-7cfbc380-0a2a-11ea-8016-a90c94bae3dc.png)
![mrm receiving 3](https://user-images.githubusercontent.com/54825571/69041450-7cfbc380-0a2a-11ea-8405-331bdeccc1f8.png)

**Comment by HannahCastro** [comment]
> Still no option for the user to go back on the previous module.
> Submission of MRM not working.
> 
> Project name should be system generated.
> 
> ![mrm receiving](https://user-images.githubusercontent.com/54825571/69041451-7cfbc380-0a2a-11ea-97da-c48a7fa3491a.png)
> ![mrm receiving 1](https://user-images.githubusercontent.com/54825571/69041445-7c632d00-0a2a-11ea-9869-b6bf2e682f92.png)
> ![mrm receiving 2](https://user-images.githubusercontent.com/54825571/69041447-7cfbc380-0a2a-11ea-8016-a90c94bae3dc.png)
> ![mrm receiving 3](https://user-images.githubusercontent.com/54825571/69041450-7cfbc380-0a2a-11ea-8405-331bdeccc1f8.png)

For the Project Name, system should get it from the Ship To field in the PO.

**Comment by agiebanez** [comment]
MRM preparation  now working.

![mrm rec com](https://user-images.githubusercontent.com/54825571/70122003-c09d3100-16aa-11ea-8d29-a2481cd7d6e9.png)
