### ISSUE TITLE
Typographical errors in pop-up messages

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#66]
**Describe the bug**
There are typographical errors in the pop-up messages.

**Expected behavior**
_Pop-up message when resetting password: Should be "Try thinking of something new."_
![image](https://user-images.githubusercontent.com/51902789/64831050-75710600-d606-11e9-9524-82430585bb94.png)
_Pop-up message when submitting created PO: Should be "finalizing."_
![image](https://user-images.githubusercontent.com/51902789/64831013-3fcc1d00-d606-11e9-8301-30d46590e1a1.png)
_Pop-up message when submitting created JO: Should be "Success!"_
![image](https://user-images.githubusercontent.com/51902789/64830952-dc41ef80-d605-11e9-847f-2852ac41aa07.png)
_Pop-up message when rejecting JO: Should be "Reject this Job Order?"_
![image](https://user-images.githubusercontent.com/51902789/64830974-05628000-d606-11e9-86e9-3eb9e693bf0e.png)
_Pop-up message when JO is Approved or Rejected: Should be "Success!"_
![image](https://user-images.githubusercontent.com/51902789/64835706-a0188a00-d619-11e9-8190-8f449dcbb5f8.png)
![image](https://user-images.githubusercontent.com/51902789/64835944-9d6a6480-d61a-11e9-8d82-694e3bc7a5d5.png)
_Pop-up message when choosing Chain Template: Should be "Do you want to proceed with this chain template?"_
![image](https://user-images.githubusercontent.com/51902789/64836453-93496580-d61c-11e9-8d4b-ddaaa506656f.png)
_Pop-up message when rejecting a JO request (new, cancellation, closing): Should be "Please fill in the required field."_
![image](https://user-images.githubusercontent.com/51902789/65128576-486c8b00-da2c-11e9-9ae0-2327fecb87ae.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by HannahCastro** [comment]
To add:
_Pop-up message when cancelling a transaction: Should be "Are you sure you want to cancel?"_
![image](https://user-images.githubusercontent.com/51902789/65290386-9a72f500-db81-11e9-84f7-18d5caccdec8.png)
_Pop-up message when creating new storage location: Should be "Please check before finalizing."_
![image](https://user-images.githubusercontent.com/51902789/65400873-4ffaae00-ddf7-11e9-8399-0f6cd59103ed.png)

_Notification for JO approval: Should be "[JO Number] for approval"_
![image](https://user-images.githubusercontent.com/51902789/65417693-3ffdc100-de2d-11e9-81ef-502a18bd72ef.png)

**Comment by agiebanez** [comment]
![image](https://user-images.githubusercontent.com/54825571/65412340-9c5ae380-de21-11e9-9cb1-a16393045a4a.png)

**Comment by HannahCastro** [comment]
> _Notification for JO approval: Should be "[JO Number] for approval"_
> ![image](https://user-images.githubusercontent.com/51902789/65417693-3ffdc100-de2d-11e9-81ef-502a18bd72ef.png)

Change made was confusing as it only uses the last 3 digits of the JO Number. This should be either "JO Number LOG19-000001 for approval".
![image](https://user-images.githubusercontent.com/51902789/65734720-e0423700-e106-11e9-9ce8-ad934a0daebc.png)

**Comment by HannahCastro** [comment]
_Pop-up message when MRS is Approved: Should be "Success!"_
![image](https://user-images.githubusercontent.com/51902789/65752982-8c544400-e140-11e9-83d2-c345bd53cf0b.png)
_Pop-up message when forwarding MRM for approval: Should be "Are you sure you want to submit this MRM?"_
![image](https://user-images.githubusercontent.com/51902789/65847150-f05e4e80-e372-11e9-80ce-e63030a27844.png)
_Pop-up message when submitting Date Needed at Site for confirmation: Should be "Successfully forwarded Date Needed at Site for confirmation."_
![image](https://user-images.githubusercontent.com/51902789/65847373-dffaa380-e373-11e9-85ac-9ca7bf99de13.png)

**Comment by HannahCastro** [comment]
The following have been resolved:
![image](https://user-images.githubusercontent.com/51902789/74115706-64471800-4beb-11ea-8e9f-76aeab561f8f.png)
