### ISSUE TITLE
TS87: Canvasser is not notified with the rejected JO and remarks can't be seen by the Canvasser

### ISSUE THREAD

**Issue by jtuppal** [vasavah/vsv-fli-grn#67]
**Describe the bug**
Logistics Head rejected the JO and remarks was encoded since this is mandatory. However, canvasser doesn't receive any notifications to update him on the rejection and for re-JO. Remarks which is also the instruction provided by Logistics Head can't be viewed by the canvasser as well. No audit trail

**To Reproduce**
1. Go to Job Order
2. Click pending JO then view
3. Click Reject
4. Encode Remarks
5. Click Reject

At Canvasser's page, there's no notification of the rejection and remarks can't be seen.
1. Go to Job Order
2. Click JO with rejected status then view
3. Click Edit Job Order

For the no audit trail (User: Logistics Head)
1. Click Report

**Expected behavior**
Canvasser will be notified on the rejection of JO and remarks will be viewed for them to know what should be revised

**Screenshots**
![image](https://user-images.githubusercontent.com/54651933/64155198-e9701900-ce64-11e9-8d4a-1765eba39662.png)

![image](https://user-images.githubusercontent.com/54651933/64155039-a44be700-ce64-11e9-9ad0-97f19f74c591.png)

![image](https://user-images.githubusercontent.com/54651933/64154454-82059980-ce63-11e9-996d-8abd3764ee8e.png)

**Desktop (please complete the following information):**
OS: [Windows 10 Pro]
Browser [Google Chrome]
Version [76.0.3809.132]

**Comment by HannahCastro** [comment]
To add, Logistics Head can't see the items that are part of that JO. Logistics Head should be able to all details of a JO to make an informed decision in approving or rejecting a request.
![image](https://user-images.githubusercontent.com/51902789/64835423-89256800-d618-11e9-9756-c496fb35f75e.png)

**Comment by jtuppal** [comment]
Canvasser is notified of rejection and remarks are displayed also.
