### ISSUE TITLE
TS2: Logistics Head Dashboard

### ISSUE THREAD

**Issue by jtuppal** [vasavah/vsv-fli-grn#69]
Everything should be clickable and will be filtered accordingly to the selected status.
![image](https://user-images.githubusercontent.com/54651933/64840241-238fa680-d62d-11e9-920b-defe7c8446ba.png)

Also, this table should show the list of items that are filtered. Table should contain Project, PO Number, JO Number, Item Description, Qty, Supplier, Canvasser, Logistics Coordinator, Delivery Date, Actual Delivery Date, Remaining Balance, Logistics Remarks.

![image](https://user-images.githubusercontent.com/54651933/64840368-cd6f3300-d62d-11e9-96a6-22317c98a623.png)

**Comment by jtuppal** [comment]
Desktop (please complete the following information):
OS: [Windows 10 Pro]
Browser [Google Chrome]
Version [76.0.3809.132]

**Comment by HannahCastro** [comment]
Team Code filter will be replaced with Canvasser.
![image](https://user-images.githubusercontent.com/51902789/66189518-81f3f600-e6bc-11e9-8a8a-d22178dd2b63.png)

**Comment by VCI-Jojo** [comment]
@HannahCastro Kindly validate on your end if we can already close this ticket. Thank you.

**Comment by HannahCastro** [comment]
@jtuppal Please validate if Logistics Head dashboard is okay with you.

**Comment by jtuppal** [comment]
Let's meet tomorrow 8AM to finalize EGRN concerns pending with Logistics. Let me know if schedule works with you.


Thanks & Regards,


Jennifer Tuppal

SUPPLY CHAIN MANAGEMENT

Filinvest Alabang Inc.

Tel No. 8460278 loc. 6140



________________________________

**Comment by HannahCastro** [comment]
@VCI-Jojo requesting to assist us in closing this ticket. Thanks!
