### ISSUE TITLE
TS137: Chain template appeared in Supplier's account is different from the Forwarder's account (next receiver in the JO)

### ISSUE THREAD

**Issue by jtuppal** [vasavah/vsv-fli-grn#72]
**Describe the bug**
In the same PO and JO number, chain template appeared in Supplier's account is different from the Forwarder's account (next receiver in the JO)

**To Reproduce**
For this PO (Under Supplier's account), Chain template is Testing > Soonest Global > MAR Logistics. See below:
![image](https://user-images.githubusercontent.com/54651933/64842996-74f06380-d636-11e9-8399-455e438ef0e3.png)

And in that same PO but under the supposed to be the next receiver which is "testing" account, chain template appeared was Ex Logistics > Mondragon FW1 > VS Logistics
![image](https://user-images.githubusercontent.com/54651933/64843304-62c2f500-d637-11e9-8fa6-1165f533a13a.png)

**Expected Behavior**
The Chain template assigned by the Logistics Coordinator should be the one followed and considered. Any changes made by the Logistics Coordinator should be updated and aligned to all other users.

**Comment by jtuppal** [comment]
Desktop (please complete the following information):
OS: [Windows 10 Pro]
Browser [Google Chrome]
Version [76.0.3809.132]

**Comment by LAValera** [comment]
Chain template that LC set is displayed on all user access already but there is a problem with the display of the tracking when chain template is changed. See additional ticket
--

![Capture](https://user-images.githubusercontent.com/54824392/69204202-2fde3580-0b81-11ea-9c97-7ea241a117a5.PNG)
![Capture2](https://user-images.githubusercontent.com/54824392/69204203-2fde3580-0b81-11ea-8190-ea7c586292b1.PNG)

**Comment by HannahCastro** [comment]
@jtuppal for your closing.

**Comment by VCI-Jojo** [comment]
@HannahCastro closing this issue as per previous comment.
