### ISSUE TITLE
TS137: No Receive button

### ISSUE THREAD

**Issue by jtuppal** [vasavah/vsv-fli-grn#73]
This forwarder warehouse doesn't have Receive button to confirm acceptance of the items from the supplier / other warehouse.

![image](https://user-images.githubusercontent.com/54651933/64844872-63f62100-d63b-11e9-954c-3bbee7de9dd9.png)
![image](https://user-images.githubusercontent.com/54651933/64844883-6bb5c580-d63b-11e9-8831-5862a92af963.png)
![image](https://user-images.githubusercontent.com/54651933/64844893-71aba680-d63b-11e9-9575-a5a208c065e9.png)

**Comment by jtuppal** [comment]
Desktop (please complete the following information):
OS: [Windows 10 Pro]
Browser [Google Chrome]
Version [76.0.3809.132]

**Comment by HannahCastro** [comment]
@jtuppal for your closing.

**Comment by LAValera** [comment]
This issue still occurs. The first user in the chain will only able to receive shipment when Logistics   Coordinator changes Chain Template. This issue persists on several chain templates.

**Comment by LAValera** [comment]
Issue resolved. You can receive/release already as long as the correct account is used.

**Comment by HannahCastro** [comment]
> Issue resolved. You can receive/release already as long as the correct account is used.

@jtuppal for closing of this ticket.
