### ISSUE TITLE
TS95: The Approve JO button is not available for LH if Date Needed at Site is not yet confirmed. This should be simultaneous.

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#76]
**Describe the bug**
There is no status/remark that shows Logistics Head that the Date Needed at Site is not yet confirmed by PTH. LH can't proceed with JO approval when DNS isn't confirmed yet. This should be simultaneous with the waiting of confirmation. JO Approval should be allowed so that it LH could assign the JO to a Logistics Coordinator and move forward. When DNS is not confirmed by PTH, the LH is not allowed to approve the JO.

**To Reproduce**
-Create a PO
-Create a JO
-Go to Logistics Head access
-View JO
-See Error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54824392/65094666-7cc25600-d9f0-11e9-9ddd-392d4f2285f8.png)

**Desktop (please complete the following information):**
 - Device: [Desktop]
 - OS: [Windows 7]
 - Browser [Chrome]
 - Version 77.0.3865.75 (Official Build) (64-bit)

**Comment by HannahCastro** [comment]
As previously discussed (eGRN Process Flow v3), Logistics Head will either approve or reject the Job Order.
- If Logistics Head will reject the JO, they will have to indicate reason for rejection in order to proceed.
- If Logistics Head will approve the JO, they will assign the JO to a Logistics Coordinator and submit the Date Needed at Site for confirmation of the PTH/PIC assigned.

**Comment by zetaleona** [comment]
Hi!

This is for clarification only. 

- If the Logistics Head submits the date needed at the site to PTH/PIC and the PTH/PIC changed the date needed at the site, what will be the next step? Who will be the approver of the date changed?

**Comment by HannahCastro** [comment]
There will be no approval workflow for changing the Date Needed at Site. We follow the date that the site indicated. Once PTH/PIC confirms or changes the Date Needed at Site, the system will accept the action done.

Please note that we have set 14 calendar days for the PTH/PIC to confirm or change the Date Needed at Site. After 14 calendar days without any action done, system will automatically confirm the initial date.

**Comment by agiebanez** [comment]
Additional:

![DATE CHANGES1](https://user-images.githubusercontent.com/54825571/65575098-95f37580-dfa1-11e9-983e-5490dfec2a8d.png)

**Comment by zetaleona** [comment]
> There will be no approval workflow for changing the Date Needed at Site. We follow the date that the site indicated. Once PTH/PIC confirms or changes the Date Needed at Site, the system will accept the action done.
> 
> Please note that we have set 14 calendar days for the PTH/PIC to confirm or change the Date Needed at Site. After 14 calendar days without any action done, system will automatically confirm the initial date.

Hi! 

This is noted. Thank you

**Comment by LAValera** [comment]
Logistics Head can set the date needed at site during approval. Setting the date needed at site by PTH/PIC does not stop the process of approval anymore by LH. Once PTH/PIC sets a new date needed at site it updates and notifies the Logistics Coordinator.
