### ISSUE TITLE
TS60: Manual encoding of price in BOQ during PO creation is not possible.

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#8]
**Describe the bug**
Price can't be manually encoded during PO creation

**To Reproduce**
1. Go to 'PO Management'
2. Click on 'Create New PO'
3. Scroll down to the BOQ List

**Expected behavior**
Can not select Delivery Date, PO Number and can not search can not be selected. Price can't be manually encoded too.

**Screenshots**
![image](https://user-images.githubusercontent.com/54824392/64749927-fb7b4700-d549-11e9-9048-a353487c4ee4.png)

**Desktop
 - Device: [Desktop]
 - OS: [Windows 7]
 - Browser [Chrome]
 - Version [Version 77.0.3865.75 (Official Build) (64-bit)]

**Additional context**

**Comment by HannahCastro** [comment]
Please see ticket #179 for the solution and ticket #180 for additional requirement.

**Comment by LAValera** [comment]
Created ticket #s 179 and 180 for the solution.
