### ISSUE TITLE
TS145.1: Receive goods button can't be found in all the stops in the chain template.

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#83]
**Describe the bug**
Can't receive goods after the 1st stop in the chain template. (Triple H Logistics-Danitech-testing). Only "Triple H Logistics" was the only one to receive goods. "Danitech" and "testing" was not able receive goods because the receive goods button was not available.

**To Reproduce**
-After creating PO, creating JO, confirming date needed on site, approving JO and assigning JO to LC
-Open the user access of the stops in the chain template
-Scroll down below and see error

**Expected behavior**
Receive goods should be available in all the stops of the selected chain template

**Screenshots**
![image](https://user-images.githubusercontent.com/54824392/65102871-0e38c480-d9ff-11e9-8e6f-f129aaa0c6a2.png)
![image](https://user-images.githubusercontent.com/54824392/65102902-23155800-d9ff-11e9-87d8-2ac8f1997fbc.png)

**Desktop (please complete the following information):**
 - Device: [Desktop]
 - OS: [Windows 7]
 - Browser [Chrome]
 - Version 77.0.3865.75 (Official Build) (64-bit)

**Comment by agiebanez** [comment]
In addition:

User cannot receive the shipment as tracking and receive button is missing. 

![image](https://user-images.githubusercontent.com/54825571/65492044-cf18e080-dee2-11e9-86b7-14b22b86470e.png)

**Comment by LAValera** [comment]
Receive Goods/Release buttons are available already.
