### ISSUE TITLE
TS76.1:Can not create another JO to replace cancelled JO. The cancelled JO is tagged as delivered

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#84]
**Describe the bug**
For example, you created a 2 JOs for a single PO, then 1 JO was cancelled. You can not replace the cancelled JO. No "Create New JO" option once this scenario happens. And the status in the JO list of the cancelled JO is tagged as "Delivered".

**To Reproduce**
-Create a PO
-Create 2 JOs for the PO
-Cancel a JO under the PO of choice
-View PO page and see the error of lacking "create new JO button" and the status in the JO list of the cancelled JO is "Delivered".

**Expected behavior**
Once a JO is cancelled, the quantity of the cancelled JO should still be available for creation. The system should allow the user to create a new JO to replace the cancelled one. The status of the cancelled JO should be tagged as "cancelled" and not "Delivered"

**Screenshots**
![image](https://user-images.githubusercontent.com/54824392/65105579-f9146380-da07-11e9-834f-66d9e085b081.png)
![image](https://user-images.githubusercontent.com/54824392/65105629-1fd29a00-da08-11e9-98f7-2b6c1329f1b0.png)

**Desktop (please complete the following information):**
 - Device: [Desktop]
 - OS: [Windows 7]
 - Browser [Chrome]
 - Version 77.0.3865.75 (Official Build) (64-bit)

**Comment by HannahCastro** [comment]
To add context to the wrong status, when viewing the JO that was cancelled, the status is CANCELLED. However, when viewing the JO in the List of JO, the status is DELIVERED.

Since JO is cancelled, the items and quantity of that JO should be available for JO (Remaining Quantity).

**Comment by LAValera** [comment]
Canvasser can create new JO already once the JO cancellation has been approved.
