### ISSUE TITLE
TS145.2: System prevented to proceed when the expected quantity is equal to the received quantity during receiving stage/module. User is site receiver

### ISSUE THREAD

**Issue by agiebanez** [vasavah/vsv-fli-grn#92]
**Describe the bug**
System prevented to proceed when the expected quantity is equal to the received quantity.  It will only proceed if the quantity is less than the expected quantity. Also, the system stopped when I tried to edit or update. Changes were not updated and cannot retrieve the previous page / module.

**Expected behavior**
System should allow the site receiver to proceed when the expected quantity is the same/exact with the quantity received as stated in TS 145. System should also save all the updates.

Additional request not in TS 145: Should have a field for the name of the receiver. Full name with middle initial is required. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54825571/65136578-60e3a200-da3a-11e9-80e1-a6a20693c098.png)

**Comment by HannahCastro** [comment]
Another example:
![image](https://user-images.githubusercontent.com/51902789/65574781-ec13e900-dfa0-11e9-9aa0-7a112814c947.png)

**Comment by agiebanez** [comment]
System allowed site receiver to proceed. But project name should be system generated. DR number did not transfer in the MRM details. 

![mrm creation 1](https://user-images.githubusercontent.com/54825571/69042548-58a0e680-0a2c-11ea-9640-76748d093618.png)
![mrm creation 2](https://user-images.githubusercontent.com/54825571/69042550-58a0e680-0a2c-11ea-980f-46c63ca11b91.png)
![mrm receiving 2](https://user-images.githubusercontent.com/54825571/69042554-59397d00-0a2c-11ea-8e5b-7ba129dcc3c4.png)

**Comment by HannahCastro** [comment]
> System allowed site receiver to proceed. But project name should be system generated. DR number did not transfer in the MRM details.
> 
> ![mrm creation 1](https://user-images.githubusercontent.com/54825571/69042548-58a0e680-0a2c-11ea-9640-76748d093618.png)
> ![mrm creation 2](https://user-images.githubusercontent.com/54825571/69042550-58a0e680-0a2c-11ea-980f-46c63ca11b91.png)
> ![mrm receiving 2](https://user-images.githubusercontent.com/54825571/69042554-59397d00-0a2c-11ea-8e5b-7ba129dcc3c4.png)

In addition, system doesn't have yet the field to enter the fully name of the receiver.

**Comment by agiebanez** [comment]
Issue resolved.
