### ISSUE TITLE
TS126: System allowed adding incomplete Shipment Details

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-grn#96]
**Describe the bug**
System allowed Logistics Coordinator to proceed with submitting shipment details even if the fields are not complete.

**To Reproduce**
1. Go to notifications then click JO to be processed.
2. Click on 'Edit Shipment Details' and input some details.
3. See error

**Expected behavior**
If Logistics Coordinator will start inputting details for LC Application and Forwarder Bidding, system should prompt error and not allow user to proceed if not all fields were filled up.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/65291187-d065a880-db84-11e9-8215-ee0dc1286bc9.png)
![image](https://user-images.githubusercontent.com/51902789/65292122-c2b22200-db88-11e9-8f3c-d8fc74fbb87a.png)
![image](https://user-images.githubusercontent.com/51902789/65292166-f2612a00-db88-11e9-83a1-5970e3490c9a.png)
![image](https://user-images.githubusercontent.com/51902789/65292233-2f2d2100-db89-11e9-8177-fb4fd3730d74.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by zetaleona** [comment]
Hi Hannah!

**Comment by HannahCastro** [comment]
Upon further discussion, fields under LC Application and Forwarder Bidding should not be required. This ticket will be closed.
